---
- name: Remove docker and docker-runc
  zypper:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-runc
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success

- name: Install docker
  command: "zypper install -y --force-resolution --replacefiles {{ docker_version_map[docker_version]['package'] }} acl"
  args:
    warn: false

# Workaround for https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/155#issuecomment-1117069430
- name: Uninstall nscd 
  zypper:
    name: nscd
    state: absent
