---
- name: Remove docker
  package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-ce
    - podman
    - podman-remote
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success

- name: Set container_group = podman
  set_fact:
    container_group: "podman"

- name: disable SELinux
  selinux:
    state: disabled

- name: Install podman
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - podman-3.4.2
    - podman-remote-3.4.2

- name: reload daemon
  systemd:
    daemon_reload: yes


