---
- name: Stop the podman service
  systemd:
    name: podman.service
    state: stopped

- name: Configure podmanapi.service
  template:
    src: podmanapi.service
    dest: /usr/lib/systemd/user/podmanapi.service

- name: alias docker and use socket
  template:
    src: docker.alias
    dest: /usr/bin/docker
    mode: 0755

- name: set Temporary storage location
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: "^runroot = "
    line: runroot = "/mnt/data/docker/runroot/"
    backrefs: yes
    create: yes

- name: set Primary Read/Write location of container storage
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: "^graphroot = "
    line: graphroot = "/mnt/data/docker/graphroot/"
    backrefs: yes
    create: yes

- name: set location of container storage for rootless
  lineinfile:
    path: /etc/containers/storage.conf
    insertafter: '^# rootless_storage_path = '
    line: rootless_storage_path = "/mnt/data/docker/rootless/$UID/"
    create: yes

- name: set overlay2 storage driver
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: "^driver = "
    line: driver = "overlay2"
    backrefs: yes
    create: yes

# For some reason, podman services cannot start with user elastic unless we reboot
- name: enable linger for elastic user
  shell: loginctl enable-linger elastic

- name: Reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection

- name: Start the podman socket
  systemd:
    name: podman.socket
    enabled: yes
    scope: user
    daemon_reload: true
  become: yes
  become_method: sudo
  become_user: elastic

- name: Start the podman service
  systemd:
    name: podmanapi.service
    enabled: yes
    scope: user
    daemon_reload: true
  become: yes
  become_method: sudo
  become_user: elastic
